### ISSUE TITLE
Plugins removed?

### ISSUE THREAD

**Issue by itsOnly1Jah** [NixNeovim/NixNeovimPlugins#61] opened 2023-05-04 16:33 UTC
I noticed today after updating my nix flake that  I was unable to rebuild due to `mason` and  `mason-lspconfig` . I think my additions to the manifest got dropped with the previous commit

**Comment by jooooscha** [comment] 2023-05-05 08:00
I just reran the workflow. Apparently, there is some error while updating the mentioned plugins.


![image](https://user-images.githubusercontent.com/57965027/236405478-a5540478-c4b6-415b-92f4-d10146640c0a.png)

Will look into it. Thanks for noticing.

For now, please use an older commit of the repo

**Comment by jooooscha** [comment] 2023-05-05 09:17
The problem is a rate limit for GitHub's API. I have changed two things:

First, when fetching the plugin fails, the cache will be used, and, secondly, I shuffle the manifest before updating the plugins.
This gives every plugin the same chance to be in the first n plugins for which we have API calls. Otherwise, the last entries in the manifest would have a much lower chance of being updated.

I hope this workaround, solves this for now.
In the long run, the update script should probably support partial updates, which makes this issue related to #3 (and #54).

**Comment by jooooscha** [comment] 2023-07-19 09:03
I have just merged https://github.com/NixNeovim/NixNeovimPlugins/pull/71 (which replaced https://github.com/NixNeovim/NixNeovimPlugins/pull/54), I hope this solves your issue.

Please reopen, if something like this does occur again.

**Closed by jooooscha** 2023-07-19 09:03 UTC
